# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os  
import check_camera
import Capture_Image
import Train_Image
import Recognize
import yoklamasil
import first
import mysql.connector as mysql
import time
import datetime
from mysql.connector import Error
from PyQt5 import QtCore, QtGui, QtWidgets
if os.path.isfile("key.lock")==True:
    first.setup()
else:
    class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(535, 514)
            MainWindow.setMinimumSize(QtCore.QSize(535, 514))
            MainWindow.setMaximumSize(QtCore.QSize(535, 514))
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("X.A.N.A.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            MainWindow.setWindowIcon(icon)
            MainWindow.setStyleSheet("background-color:rgb(54, 54, 54)")
            MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Turkish, QtCore.QLocale.Turkey))
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.VHALLogo = QtWidgets.QLabel(self.centralwidget)
            self.VHALLogo.setGeometry(QtCore.QRect(150, 0, 241, 241))
            self.VHALLogo.setText("")
            self.VHALLogo.setPixmap(QtGui.QPixmap("VHAL LOGO.png"))
            self.VHALLogo.setObjectName("VHALLogo")
            self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
            self.groupBox.setGeometry(QtCore.QRect(150, 340, 241, 121))
            self.groupBox.setAutoFillBackground(False)
            self.groupBox.setStyleSheet("color:rgb(0, 0, 0); background-color: rgb(208, 208, 208); font: 87 9pt \"Segoe UI Black\";")
            self.groupBox.setTitle("")
            self.groupBox.setObjectName("groupBox")
            self.Giris = QtWidgets.QPushButton(self.groupBox)
            self.Giris.setGeometry(QtCore.QRect(150, 90, 75, 23))
            self.Giris.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
            self.Giris.setStyleSheet("background-color: rgb(236, 182, 53); color:rgb(25, 21, 20); font: 87 10pt \"Segoe UI Black\";")
            self.Giris.setObjectName("Giris")
            self.line = QtWidgets.QFrame(self.groupBox)
            self.line.setGeometry(QtCore.QRect(-17, 0, 20, 121))
            self.line.setStyleSheet("background-color:rgb(0, 0, 0)")
            self.line.setFrameShape(QtWidgets.QFrame.VLine)
            self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
            self.line.setObjectName("line")
            self.line_2 = QtWidgets.QFrame(self.groupBox)
            self.line_2.setGeometry(QtCore.QRect(0, -4, 241, 21))
            self.line_2.setStyleSheet("background-color: rgb(0, 0, 0);")
            self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
            self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
            self.line_2.setObjectName("line_2")
            self.line_3 = QtWidgets.QFrame(self.groupBox)
            self.line_3.setGeometry(QtCore.QRect(240, 10, 16, 111))
            self.line_3.setStyleSheet("background-color: rgb(0, 0, 0);")
            self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
            self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
            self.line_3.setObjectName("line_3")
            self.line_4 = QtWidgets.QFrame(self.groupBox)
            self.line_4.setGeometry(QtCore.QRect(0, 117, 251, 10))
            self.line_4.setStyleSheet("background-color: rgb(0, 0, 0);")
            self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
            self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
            self.line_4.setObjectName("line_4")
            self.line_5 = QtWidgets.QFrame(self.groupBox)
            self.line_5.setGeometry(QtCore.QRect(237, 10, 20, 121))
            self.line_5.setStyleSheet("background-color:rgb(0, 0, 0)")
            self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
            self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
            self.line_5.setObjectName("line_5")
            self.Yoklama_Al = QtWidgets.QPushButton(self.groupBox)
            self.Yoklama_Al.setGeometry(QtCore.QRect(20, 90, 81, 23))
            self.Yoklama_Al.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
            self.Yoklama_Al.setStyleSheet("background-color: rgb(154, 241, 22); color:rgb(25, 21, 20); font: 87 10pt \"Segoe UI Black\";")
            self.Yoklama_Al.setObjectName("Yoklama_Al")
            self.layoutWidget = QtWidgets.QWidget(self.groupBox)
            self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 224, 52))
            self.layoutWidget.setObjectName("layoutWidget")
            self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
            self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout_3.setObjectName("verticalLayout_3")
            self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_3.setObjectName("horizontalLayout_3")
            self.KullaniciAdi = QtWidgets.QLabel(self.layoutWidget)
            self.KullaniciAdi.setObjectName("KullaniciAdi")
            self.horizontalLayout_3.addWidget(self.KullaniciAdi)
            self.KullaniciAdiInput = QtWidgets.QLineEdit(self.layoutWidget)
            self.KullaniciAdiInput.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
            self.KullaniciAdiInput.setText("")
            self.KullaniciAdiInput.setObjectName("KullaniciAdiInput")
            self.horizontalLayout_3.addWidget(self.KullaniciAdiInput)
            self.verticalLayout_3.addLayout(self.horizontalLayout_3)
            self.horizontalLayout = QtWidgets.QHBoxLayout()
            self.horizontalLayout.setObjectName("horizontalLayout")
            self.Sifre = QtWidgets.QLabel(self.layoutWidget)
            self.Sifre.setObjectName("Sifre")
            self.horizontalLayout.addWidget(self.Sifre)
            self.SifreInput = QtWidgets.QLineEdit(self.layoutWidget)
            self.SifreInput.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
            self.SifreInput.setText("")
            self.SifreInput.setEchoMode(QtWidgets.QLineEdit.Password)
            self.SifreInput.setObjectName("SifreInput")
            self.horizontalLayout.addWidget(self.SifreInput)
            self.verticalLayout_3.addLayout(self.horizontalLayout)
            self.label = QtWidgets.QLabel(self.centralwidget)
            self.label.setGeometry(QtCore.QRect(23, 260, 491, 61))
            self.label.setStyleSheet("color: rgb(231, 231, 231); font: 24pt \"Ravie\";")
            self.label.setObjectName("label")
            self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
            self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
            self.layoutWidget1.setObjectName("layoutWidget1")
            self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
            self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout_2.setObjectName("verticalLayout_2")
            MainWindow.setCentralWidget(self.centralwidget)
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            MainWindow.setStatusBar(self.statusbar)

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Yoklama Sistemi"))
            self.Giris.setText(_translate("MainWindow", "Giriş Yap"))
            self.Yoklama_Al.setText(_translate("MainWindow", "Yoklama Al"))
            self.KullaniciAdi.setText(_translate("MainWindow", "Kullanıcı Adı:"))
            self.Sifre.setText(_translate("MainWindow", "Şifre                :"))
            self.label.setText(_translate("MainWindow", "VHAL Yoklama Sistemi"))
        
        def Kurulum_Yap(self):
            first.setup()
            
        def kameraKontrol(self):
            check_camera.camer()
                
        # --------------------------------------------------------------


        def ogrenciTanit():
            Capture_Image.takeImages()
        # -----------------------------------------------------------------


        def Trainimages():
            Train_Image.TrainImages()
        # --------------------------------------------------------------------


        def YoklamaBaslat():
            Recognize.recognize_attendence()  
        # --------------------------------------------------------------------

        def YoklamaSil():
            yoklamasil.tarih_sil()
        # --------------------------------------------------------------------




    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
        
    
    


